### ISSUE TITLE
Is $expand attribute not considered correctly? 

### ISSUE THREAD

**Issue by ChrisMalewski** [FraunhoferIOSB/FROST-Python-Client#27]
Dear FROST-Team,
when I try to request filtered datastreams with expanded Observations

`sta.datastreams().query().expand(obs_expand).filter(ds_filter).select("id", "phenomenonTime", "properties").list()`

with `obs_expand=Observations($select=result,phenomenonTime;$orderby=phenomenonTime desc;$top=2)`

The `$top=2` statement seems to be ignored. However excecuting the composed request in a browser gives the expected result.

http://<sta>/v1.1/Datastreams?%24expand=Observations%28%24select%3Dresult%2CphenomenonTime%3B%24orderby%3DphenomenonTime+desc%3B%24top%3D2%29&%24filter=id+eq+9021&%24select=id%2CphenomenonTime%2Cproperties

Can you reproduce the behaviour?

Cheers

**Comment by vogljonathan** [comment]
Thank you for using the Frost Client. I have tested your example with `obs_expand="Observations($select=result,phenomenonTime;$orderby=phenomenonTime desc;$top=2)"` as string and can't reproduce your problem, I get the respective top number of responses. However, these observations have not received any IDs, so I have created a separate issue #28  for them, as I did not interpret this as your problem.
I could imagine that you are iterating over the observations and therefore getting more than 2 entities. In this case note that in your example you have to iterate over `observations_object.entities` (Python List) and not directly on the EntityList, for details see the readme or issue #17 . If your problem is somewhere else, please give us some more code so we can help you to solve it.

**Comment by ChrisMalewski** [comment]
Considering the Observation($select)-Statement I do expect to get result and phenomenonTime.
Can you provide me with a working code example of your code?
Which version of Frost-Python-Client do you use?
Tanks in advance.

**Comment by vogljonathan** [comment]
Based on the example at https://fraunhoferiosb.github.io/FROST-Server/deployment/docker.html with two datastreams, the following code provides me with the desired attributes:

`import frost_sta_client as fsc

service = fsc.SensorThingsService("http://localhost:8080/FROST-Server/v1.1")
obs_expand="Observations($select=result,phenomenonTime;$orderby=phenomenonTime desc;$top=2)"
ds_filter ="id eq 1"
response = service.datastreams().query().expand(obs_expand).filter(ds_filter).select("id", "phenomenonTime", "properties").list()
datastream_list = response.entities
single_datastream = datastream_list[0]
observations_of_single_datastream = single_datastream.observations.entities
single_observation = observations_of_single_datastream[0]
result = single_observation.result
phenomenon_time = single_observation.phenomenon_time`

I am using the latest version (1.1.45). I hope this helps you to solve your problem :)

**Comment by ChrisMalewski** [comment]
Now I see the point. It seems to make a difference, if you call 
`        1. print(len(list(datastream_list[0].observations.entities)))`
`        2. print(len(list(datastream_list[0].observations)))`
In 1. only the requested observations are returned. In 2. all observations are returned, which lasts up to 20 minutes for high frequential datastreams. Is that the expected behaviour?

Are you able to reproduce that behaviour?

**Comment by vogljonathan** [comment]
Yes, that is the intended behaviour. In the first case you get a Python list. In the second case, it is an EntityList that implements its own iterator, which ensures that all elements are loaded via nextLink (in the case that there are more elements than a single request returns). This also happens sequentially, which with `$top=2` leads to a significantly larger number of server requests and therefore a longer duration than with a higher top value or the default value of the server. Top only changes the number of response entities per server request, but this is not a filter that determines the total number of matching entities.
I think this should already be covered by the explanation in the readme and the pull request #17 . I hope it is clearer to you now anyway.
