### ISSUE TITLE
Datastream.unitOfMeasurement is a JSONObject

### ISSUE THREAD

**Issue by securedimensions** [FraunhoferIOSB/FROST-Python-Client#32]
# Description
According to the [SensorThings API Standard v1.1](https://docs.ogc.org/is/18-088/18-088.html) (Table 10. Properties of a Datastream entity) the `unitOfMeasurement` property is a `JSONObject`

# Datastream.py code
The implementation enforces that the `unitOfMeasurement` is of type `UnitOfMeasurement`:
```PYTHON
    @unit_of_measurement.setter
    def unit_of_measurement(self, value):
        if value is None or isinstance(value, unitofmeasurement.UnitOfMeasurement):
            self._unit_of_measurement = value
            return
        raise ValueError('unitOfMeasurement should be of type UnitOfMeasurement!')
```

**Comment by reraroru** [comment]
Indeed. Time values are currently stored as Strings. They should be converted using an appropriate datetime class.

**Comment by reraroru** [comment]
The main purpose of the FROST Python Client is the translation between the SensorThings json format and Python class instances. SensorThings UnitOfMeasurement is modelled as a Python class UnitOfMeasurment.
