### ISSUE TITLE
How to batch POST things

### ISSUE THREAD

**Issue by C-Loftus** [FraunhoferIOSB/FROST-Python-Client#41]
I am working with a dataset where there are hundreds of sensors which can be represented as a `thing`.  I did not see any functionality in the client library to batch POST so I tried to transform the entity into json and then batch. I get no error message but no things show up in the server.

The client-side json serialization does not throw any errors and the post returns a 200 status code. I was wondering if there is a better way to batch POST in this library since to my understanding, data arrays are only for observations. 

I am working with a fresh DB with no Things inside of it and `fraunhoferiosb/frost-server-http:2.0` Docker image 

Thank you for your work on this client

## Relevant Code 

Batch as JSON

```py
def send_to_frost(things: list[fsc.Thing]):
    frost_url = os.getenv("WIS2BOX_API_BACKEND_URL")
    if not frost_url:
        raise Exception(
            "Frost API backend env var 'WIS2BOX_API_BACKEND_URL' not defined in env vars"
        )
    service = fsc.SensorThingsService(frost_url)

    if not service:
        raise Exception("Can't connect to FROST API backend")

    batch = []
    for thing in things:
        jsonVersion = utils.transform_entity_to_json_dict(thing)
        batch.append(
            {
                "id": thing.name,
                "method": "post",
                "url": "Things",
                "body": jsonVersion,
            }
        )

    payload = json.dumps({"requests": batch})

    resp = requests.post(f"{frost_url}/$batch", json=payload, headers={"Content-Type": "application/json"})

    if resp.status_code != 200:
        raise Exception(resp.text)
```

Create things

<details>
<summary>
Code to creating the fsc.Thing list. This has no client-side errors and when I post this to FROST with a for loop and service.create(thing) for every thing in the list, it posts fine.
</summary>

```py
def to_sta(
    geometry: dict[str, geojson.Feature],
    observations: Generator[PredictionsCSV, None, None],
) -> list[fsc.Thing]:
    observationMapping: dict[str, list[fsc.Observation]] = {}
    # map the COMID to the datastream
    datastreamMapping: dict[str, fsc.Datastream] = {}

    observations = list(observations) # just using a list right now to make the code more readable, will optimize generator later

    for obs in observations:
        fscObservation = fsc.Observation(
            result_quality="Prediction",
            feature_of_interest=fsc.FeatureOfInterest(
                name=str(obs["COMID"]),
                description=str(obs["COMID"]),
                encoding_type="application/json",
                feature="Chlorophyll a prediction",
            ),
            result=obs["pred"],
            phenomenon_time=f"{obs['date']} 00:00:00Z",
            result_time=f"{obs['date']} 00:00:00Z",
        )

        associatedObservations = observationMapping.get(obs["COMID"])
        if associatedObservations:
            associatedObservations.append(fscObservation)
        else:
            observationMapping[obs["COMID"]] = [fscObservation]



    for obs in observations:
        # If it is already a datastream, skip it
        if obs["COMID"] in datastreamMapping.keys():
            continue
        elif obs["COMID"] is None:
            continue

        associatedObservation = observationMapping[obs["COMID"]]

        datastream = fsc.Datastream(
            name=f"Chlorophyll a prediction at COMID {obs['COMID']}",
            description=f"Chlorophyll a prediction at COMID {obs['COMID']}",
            observed_property=fsc.ObservedProperty(
                name="Chlorophyll a prediction",
                definition="Chlorophyll a prediction",
                description="Chlorophyll a prediction",
            ),
            # required
            unit_of_measurement=fsc.UnitOfMeasurement(
                name="Chlorophyll a prediction",
                symbol="Chlorophyll a prediction",
                definition="Chlorophyll a prediction",
            ),
            observation_type="Chlorophyll a prediction",
            observed_area=geometry[obs["COMID"]],
            sensor=fsc.Sensor(
                name="Chlorophyll a prediction based on Landsat",
                description="Chlorophyll a prediction based on Landsat",
                encoding_type="Unknown",
                metadata="Unknown",
            ),
            observations=associatedObservation,
            properties={},
        )
        datastreamMapping[obs["COMID"]] = datastream

    # map the COMID to the thing
    thingsMapping: dict[str, fsc.Thing] = {}
    # Create the things objects based on the geojson
    for comid, geo in geometry.items():
        associatedDatastream = datastreamMapping.get(comid)
        if not associatedDatastream:
            continue
        thingsMapping[comid] = fsc.Thing(
            name=f"COMID {comid}",
            description=f"COMID {comid}",
            locations=[
                fsc.Location(
                    name=f"COMID {comid}",
                    encoding_type="application/json",
                    description=f"COMID {comid}",
                    location=geo,
                    properties={},
                )
            ],
            datastreams=[associatedDatastream],
        )

    return list(thingsMapping.values())

```
</details>

**Comment by hylkevds** [comment]
The batch request always returns a 200, unless the request itself is badly formatted. You have to parse the returned content, that will contain a response for each part of the batch request.

**Comment by C-Loftus** [comment]
Thank you for your response, so I take it then that the batch of the raw json is the proper way to do this and the client doesnt support it?

When I post the batch, there are no responses and no errors / warnings in the frost server log. Does that mean it succeeded? 

![image](https://github.com/user-attachments/assets/e7ced6b4-432a-49f2-8461-ca105574419b)

**Comment by hylkevds** [comment]
Correct, the client doesn't have support for batch request.

If the returned response is empty, there were no requests in the batch. The json you sent to the server was probably not a correct batch request. Check your JSON against the [documentation](https://fraunhoferiosb.github.io/FROST-Server/extensions/JsonBatchRequest.html).
What you post must be an object, containing an array named `requests`.

**Comment by C-Loftus** [comment]
Ok, thank you for your reply. At the moment I'm a bit stumped, I believe my json is fine. It is just the result from `transform_entity_to_json_dict` method in the client library. I looked over the code I have, same as above, and it seems fine, but I will continue taking a look and update here if I have any leads. Perhaps my payload is too large or something else.

**Comment by hylkevds** [comment]
You could try increasing the debug level on FROST to see if that gives any information.
And printing out the exact data being sent in the batch.

Large batches should not be a problem, I've posted 100MB JSON files to it, though reverse proxies sometimes cause issues with large files.

**Comment by C-Loftus** [comment]
Closing this. Not entirely sure what fixed it. In general, making smaller batches, avoiding reverse proxies, checking to make sure the iot.id value is not already present and going through and checking datatypes for all the fields seemed to help me debug when I wasn't sure how to interpret the logs.
