### ISSUE TITLE
id type STRING?

### ISSUE THREAD

**Issue by terrasense-de** [FraunhoferIOSB/FROST-Python-Client#9]
First of all, thank you for providing this great package!

It seems that the package is designed for id type LONG. When trying to create entities with id type STRING, line 113 in dao/base.py throws an error because the id value returned by the server cannot be cast as an integer:

`entity.id = int(frost_sta_client.utils.extract_value(response.headers['location']))`

Could you just change that line or is there more to enabling the use of Strings as ids?

**Comment by vogljonathan** [comment]
Closed as it is already implemented
